import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import PlaceBid from "../components/shadesMint";
import { useMoralis } from "react-moralis";

export default function Home() {
  const { isWeb3Enabled, chainId } = useMoralis();
  return (
    <div className="fullscreen">
      <Head>
        <title>Shades NFT</title>
        <meta name="description" content="Shades NFT Auction" />
      </Head>

      <div className="box">
        <div className="row content">
          <Image
            className="stussy"
            src="/Stussy (1).png"
            alt="me"
            width="124"
            height="164"
          />
          <h1 className="rainbow-text" style={{ fontSize: "70px" }}>
            Shades
          </h1>
          <Header></Header>
          <PlaceBid></PlaceBid>
        </div>
      </div>
      <div className="box">
        <div className="row content2">
          <ul>
            <h1>FAQ's & Rules</h1>
            <h2>
              Everyday a new "SHADE" is generated by taking the current price of
              ETH in USD and converting this to a hexadecimal (First 6 Digits of
              (ETH in USD*1000)) which represents an HTML Color Code. This is
              the color of the daily Shade!
            </h2>
            <p></p>
            <h2>
              Once A Bid is entered it canNOT be withdrawn, after the auction
              all bids aside from the winners bid are sent back
            </h2>
            <p></p>
            <h2>
              If you would like to increase your current bid simply enter the
              amount you would like to increase your bid by into the Input Box
            </h2>
            <p></p>
            <h2>
              Any Bid Must Increase The Current Winning Bid By At Least 0.1 ETH
            </h2>
          </ul>
          <ul className="socialLine">
            <a
              className="social"
              href="https://twitter.com/?lang=en"
              target="_blank"
              rel="noopener noreferrer"
            >
              Twitter
            </a>
            <a
              className="social"
              href="https://www.google.com/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Discord
            </a>
            <a
              className="social"
              href="https://www.google.com/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Telegram
            </a>
          </ul>
        </div>
      </div>
    </div>
  );
}
